require 'pathname'
require 'tmpdir'

module CedarTargetSpecs
  UI_SPECS_TARGET_NAME = "Specs"
  CONFIGURATION = "Release"

  PROJECT_ROOT = Pathname.new(File.dirname(__FILE__)).parent.to_s
  BUILD_DIR = File.join(PROJECT_ROOT, "build")

  class << self
    def in_project_dir
      original_dir = Dir.pwd
      Dir.chdir(PROJECT_ROOT)

      yield

      ensure
      Dir.chdir(original_dir)
    end

    def deployment_target_sdk_version
      in_project_dir do
        `xcodebuild -showBuildSettings -target #{UI_SPECS_TARGET_NAME} | grep IPHONEOS_DEPLOYMENT_TARGET | awk '{print $3 }'`.strip
      end
    end

    def deployment_target_sdk_dir
      @sdk_dir ||= %x[ xcrun -sdk iphonesimulator#{deployment_target_sdk_version} -show-sdk-path ].strip
    end

    # Xcode 4.3 stores its /Developer inside /Applications/Xcode.app, Xcode 4.2 stored it in /Developer
    def xcode_developer_dir
      `xcode-select -print-path`.strip
    end

    def build_dir(effective_platform_name)
      File.join(BUILD_DIR, CONFIGURATION + effective_platform_name)
    end

    def system_or_exit(cmd, stdout = nil)
      puts "Executing #{cmd}"
      cmd += " >#{stdout}" if stdout
      system(cmd) or raise "******** Build failed ********"
    end

    def with_env_vars(env_vars)
      old_values = {}
      env_vars.each do |key,new_value|
        old_values[key] = ENV[key]
        ENV[key] = new_value
      end

      yield

      env_vars.each_key do |key|
        ENV[key] = old_values[key]
      end
    end

    def output_file(target)
      output_dir = if ENV['IS_CI_BOX']
        ENV['CC_BUILD_ARTIFACTS']
      else
        Dir.mkdir(BUILD_DIR) unless File.exists?(BUILD_DIR)
        BUILD_DIR
      end

      output_file = File.join(output_dir, "#{target}.output")
      puts "Output: #{output_file}"
      output_file
    end

    def kill_simulator
      system %Q[killall -m -KILL "gdb"]
      system %Q[killall -m -KILL "otest"]
      system %Q[killall -m -KILL "iPhone Simulator"]
    end
  end
end

desc "Clean build directory"
task :clean_Specs do
  CedarTargetSpecs.system_or_exit "rm -rf #{CedarTargetSpecs::BUILD_DIR}/*", CedarTargetSpecs.output_file("clean")
end

desc "Build Specs"
task :build_Specs => :clean_Specs do
  CedarTargetSpecs.kill_simulator
  CedarTargetSpecs.system_or_exit "pushd #{CedarTargetSpecs::PROJECT_ROOT} && xcodebuild -target #{CedarTargetSpecs::UI_SPECS_TARGET_NAME} -configuration #{CedarTargetSpecs::CONFIGURATION} -sdk iphonesimulator clean build ARCHS=i386 && popd", CedarTargetSpecs.output_file("Specs")
end

desc "Run Specs"
task :Specs => :build_Specs do
  system "which ios-sim" or raise <<EOF


[Error] No ios-sim found. Use 'brew install ios-sim'.


EOF

  env_vars = {
    "CEDAR_REPORTER_CLASS" => "CDRColorizedReporter"
  }

  CedarTargetSpecs.with_env_vars(env_vars) do
    CedarTargetSpecs.system_or_exit "ios-sim launch #{File.join(CedarTargetSpecs.build_dir("-iphonesimulator"), "#{CedarTargetSpecs::UI_SPECS_TARGET_NAME}.app")} --devicetypeid 'com.apple.CoreSimulator.SimDeviceType.iPhone-5s' | tee /dev/stderr | grep -q ', 0 failures'";
  end
end
